# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI CD FOR CONVERTER

on:
  push:
    branches: [ dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - 
      name: Build the Docker image - Converter API
      run: docker build -f Dockerfile . --tag ${{ secrets.DOCKERHUB_IMAGE_NAME }}:${{ secrets.MAJOR }}.${{ secrets.MINOR }} --tag ${{ secrets.DOCKERHUB_IMAGE_NAME }}:latest   
    - 
      name: Login to DockerHub 
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Push to DockerHub - Converter API Versioned Tag
      run: docker push ${{ secrets.DOCKERHUB_IMAGE_NAME }}:${{ secrets.MAJOR }}.${{ secrets.MINOR }}   
    -
      name: Update Minor version
      uses: actions/checkout@v3
      with:
        name: 'MINOR'
        value: $((${{ secrets.MINOR }}+1))
        repository: ${{ secrets.PROJECT_NAME }}
        token: ${{ secrets.REPO_ACCESS_TOKEN }} 
